In [1]:
import torch
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
print(torch.__version__)


2.5.1


In [2]:
scalar = torch.tensor(7)
vector = torch.tensor([7,7])
print(scalar, vector, scalar.ndim, scalar.item(), vector.shape)


tensor(7) tensor([7, 7]) 0 7 torch.Size([2])


In [3]:
MATRIX = torch.tensor([[7, 8],
                      [9, 10]])
MATRIX

tensor([[ 7,  8],
        [ 9, 10]])

In [4]:
MATRIX[1], MATRIX.shape

(tensor([ 9, 10]), torch.Size([2, 2]))

In [5]:
# Create a random tensor of size [3, 4]
random_tensor = torch.rand(3,3, 3)
random_tensor

tensor([[[0.4811, 0.9324, 0.3793],
         [0.1289, 0.5072, 0.2383],
         [0.3079, 0.1401, 0.8412]],

        [[0.7961, 0.8318, 0.8252],
         [0.4404, 0.8831, 0.6112],
         [0.6037, 0.4930, 0.9810]],

        [[0.3655, 0.7554, 0.9512],
         [0.2365, 0.1554, 0.4594],
         [0.7279, 0.4413, 0.3014]]])

In [6]:
random_image_size_tensor = torch.rand(size=(224, 224, 3)) #height, width, colour channel
random_image_size_tensor.shape, random_image_size_tensor.ndim

(torch.Size([224, 224, 3]), 3)

In [7]:
zero = torch.zeros(size=(3,4))
zero

tensor([[0., 0., 0., 0.],
        [0., 0., 0., 0.],
        [0., 0., 0., 0.]])

In [8]:
ones = torch.ones(size=(3,4))
ones

tensor([[1., 1., 1., 1.],
        [1., 1., 1., 1.],
        [1., 1., 1., 1.]])

##Creating a range of tensors and tensors-like

In [9]:
#use torch.arange()
#torch.range is deprecated
torch.arange(0, 10)

tensor([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [10]:
one_to_ten = torch.arange(start=1, end=11, step=1)
one_to_ten

tensor([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10])

In [11]:
ten_zeros = torch.zeros_like(input=one_to_ten)
ten_zeros

tensor([0, 0, 0, 0, 0, 0, 0, 0, 0, 0])

In [12]:
float_32_tensor = torch.tensor([3.0, 6.0, 9.0], 
                               dtype=None, # datatype is a tensor of float32
                               device="cpu",  # device is the CPU
                               requires_grad=False) #wether or not to track gradients for this tensor
# autograd should not track the gradient for this tensor
float_32_tensor

tensor([3., 6., 9.])

In [13]:
float_32_tensor.dtype

torch.float32

In [14]:
float_16_tensor = float_32_tensor.to(dtype=torch.float16)
float_16_tensor

tensor([3., 6., 9.], dtype=torch.float16)

In [15]:
float_16_tensor * float_32_tensor

tensor([ 9., 36., 81.])

In [16]:
int_32_tensor = torch.tensor([3, 6, 9], dtype=torch.int32)
int_32_tensor

tensor([3, 6, 9], dtype=torch.int32)

In [17]:
float_32_tensor * int_32_tensor

tensor([ 9., 36., 81.])

In [18]:
int_32_tensor = torch.tensor([3, 6, 9], dtype=torch.float32)
int_32_tensor

tensor([3., 6., 9.])

In [19]:
float_32_tensor * int_32_tensor

tensor([ 9., 36., 81.])

In [20]:
some_tensor = torch.rand(size=(3,4))
some_tensor

tensor([[0.3588, 0.0178, 0.0952, 0.5889],
        [0.6579, 0.2101, 0.5486, 0.5546],
        [0.0075, 0.4036, 0.8761, 0.0104]])

In [21]:
#Find out  details about some tensor
some_tensor.size(), some_tensor.shape, some_tensor.ndim, some_tensor.device, some_tensor.dtype

(torch.Size([3, 4]), torch.Size([3, 4]), 2, device(type='cpu'), torch.float32)

In [22]:
print(some_tensor)
print(f"Datatype of tensor: {some_tensor.dtype}")
print(f"Shape of tensor: {some_tensor.shape}")
print(f"Device tensor is stored on: {some_tensor.device}")

#Matrix multiplication 


tensor([[0.3588, 0.0178, 0.0952, 0.5889],
        [0.6579, 0.2101, 0.5486, 0.5546],
        [0.0075, 0.4036, 0.8761, 0.0104]])
Datatype of tensor: torch.float32
Shape of tensor: torch.Size([3, 4])
Device tensor is stored on: cpu


Two main ways of performing multiplication in neural networks and deep learning:
1. Element-wise multiplication
2. Matrix mutlipcation
There are two main rules that performing matrix multiplications needs to satisfy:
1. The **inner dimensions** must match:
- `(3, 2) @ (3, 2)` won't work
- `(2, 3) @ (3, 2)` will work
- `(3, 2) @ (2, 3)` will work
2. The resulting matrix has the shape of the **outer dimensions**


In [23]:
tensor = torch.tensor([1, 2, 3])
print(tensor, "*", tensor, "=", tensor * tensor)

tensor([1, 2, 3]) * tensor([1, 2, 3]) = tensor([1, 4, 9])


### We should always try to use torch's implementation of matrix operations, because it is made for speed and optimized better than by hand, and less code

In [24]:
%%time
torch.matmul(tensor, tensor)
value = 0
for i in range(len(tensor)):
    value += tensor[i] * tensor[i]
    print(value)


tensor(1)
tensor(5)
tensor(14)
CPU times: user 1.64 ms, sys: 76 μs, total: 1.71 ms
Wall time: 1.09 ms


In [25]:
%%time
torch.matmul(tensor, tensor)

CPU times: user 299 μs, sys: 33 μs, total: 332 μs
Wall time: 324 μs


tensor(14)

In [26]:
tensor@tensor # matrix multiplication  shorthand

tensor(14)

In [27]:
#shapes for matrix multiplication
tensor_A = torch.tensor([[1, 2],
                          [3, 4],
                          [5, 6]])
tensor_B = torch.tensor([[7, 8],
                          [9, 10],
                          [11, 12]])
print(tensor_A.shape, tensor_B.shape)

torch.Size([3, 2]) torch.Size([3, 2])


In [28]:
tensor_A.shape, tensor_B.shape

(torch.Size([3, 2]), torch.Size([3, 2]))

In [29]:
tensor_B.T, tensor_B.T.shape

(tensor([[ 7,  9, 11],
         [ 8, 10, 12]]),
 torch.Size([2, 3]))

tensor([[ 23,  29,  35],
        [ 53,  67,  81],
        [ 83, 105, 127]])

In [31]:
# The operation works when tensor_B is transposed
print(f"Original shapes: tensor_A = {tensor_A.shape}, tensor_B = {tensor_B.shape}\n")
print(f"New shapes: tensor_A = {tensor_A.shape} (same as above), tensor_B.T = {tensor_B.T.shape}\n")
print(f"Multiplying: {tensor_A.shape} * {tensor_B.T.shape} <- inner dimensions match\n")
print("Output:\n")
output = torch.matmul(tensor_A, tensor_B.T)
print(output) 
print(f"\nOutput shape: {output.shape}")

Original shapes: tensor_A = torch.Size([3, 2]), tensor_B = torch.Size([3, 2])

New shapes: tensor_A = torch.Size([3, 2]) (same as above), tensor_B.T = torch.Size([2, 3])

Multiplying: torch.Size([3, 2]) * torch.Size([2, 3]) <- inner dimensions match

Output:

tensor([[ 23,  29,  35],
        [ 53,  67,  81],
        [ 83, 105, 127]])

Output shape: torch.Size([3, 3])
