In [1]:
import torch
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
print(torch.__version__)


2.5.1


In [2]:
scalar = torch.tensor(7)
vector = torch.tensor([7,7])
print(scalar, vector, scalar.ndim, scalar.item(), vector.shape)


tensor(7) tensor([7, 7]) 0 7 torch.Size([2])


In [3]:
MATRIX = torch.tensor([[7, 8],
                      [9, 10]])
MATRIX

tensor([[ 7,  8],
        [ 9, 10]])

In [4]:
MATRIX[1], MATRIX.shape

(tensor([ 9, 10]), torch.Size([2, 2]))

In [5]:
# Create a random tensor of size [3, 4]
random_tensor = torch.rand(3,3, 3)
random_tensor

tensor([[[0.8275, 0.6139, 0.4845],
         [0.5557, 0.3725, 0.7241],
         [0.1405, 0.0918, 0.0849]],

        [[0.4428, 0.3831, 0.2083],
         [0.9056, 0.4184, 0.5010],
         [0.4820, 0.6002, 0.6290]],

        [[0.6185, 0.0546, 0.2810],
         [0.5650, 0.1283, 0.2146],
         [0.9676, 0.6519, 0.5858]]])

In [6]:
random_image_size_tensor = torch.rand(size=(224, 224, 3)) #height, width, colour channel
random_image_size_tensor.shape, random_image_size_tensor.ndim

(torch.Size([224, 224, 3]), 3)

In [7]:
zero = torch.zeros(size=(3,4))
zero

tensor([[0., 0., 0., 0.],
        [0., 0., 0., 0.],
        [0., 0., 0., 0.]])

In [8]:
ones = torch.ones(size=(3,4))
ones

tensor([[1., 1., 1., 1.],
        [1., 1., 1., 1.],
        [1., 1., 1., 1.]])

##Creating a range of tensors and tensors-like

In [9]:
#use torch.arange()
#torch.range is deprecated
torch.arange(0, 10)

tensor([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [10]:
one_to_ten = torch.arange(start=1, end=11, step=1)
one_to_ten

tensor([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10])

In [11]:
ten_zeros = torch.zeros_like(input=one_to_ten)
ten_zeros

tensor([0, 0, 0, 0, 0, 0, 0, 0, 0, 0])

In [12]:
float_32_tensor = torch.tensor([3.0, 6.0, 9.0], 
                               dtype=None, # datatype is a tensor of float32
                               device="cpu",  # device is the CPU
                               requires_grad=False) #wether or not to track gradients for this tensor
# autograd should not track the gradient for this tensor
float_32_tensor

tensor([3., 6., 9.])

In [13]:
float_32_tensor.dtype

torch.float32

In [14]:
float_16_tensor = float_32_tensor.to(dtype=torch.float16)
float_16_tensor

tensor([3., 6., 9.], dtype=torch.float16)

In [15]:
float_16_tensor * float_32_tensor

tensor([ 9., 36., 81.])

In [16]:
int_32_tensor = torch.tensor([3, 6, 9], dtype=torch.int32)
int_32_tensor

tensor([3, 6, 9], dtype=torch.int32)

In [17]:
float_32_tensor * int_32_tensor

tensor([ 9., 36., 81.])

In [18]:
int_32_tensor = torch.tensor([3, 6, 9], dtype=torch.float32)
int_32_tensor

tensor([3., 6., 9.])

In [19]:
float_32_tensor * int_32_tensor

tensor([ 9., 36., 81.])

In [20]:
some_tensor = torch.rand(size=(3,4))
some_tensor

tensor([[0.8382, 0.6474, 0.7107, 0.0946],
        [0.2511, 0.4906, 0.5676, 0.0026],
        [0.5535, 0.0063, 0.1886, 0.9845]])

In [21]:
#Find out  details about some tensor
some_tensor.size(), some_tensor.shape, some_tensor.ndim, some_tensor.device, some_tensor.dtype

(torch.Size([3, 4]), torch.Size([3, 4]), 2, device(type='cpu'), torch.float32)

In [22]:
print(some_tensor)
print(f"Datatype of tensor: {some_tensor.dtype}")
print(f"Shape of tensor: {some_tensor.shape}")
print(f"Device tensor is stored on: {some_tensor.device}")

#Matrix multiplication 


tensor([[0.8382, 0.6474, 0.7107, 0.0946],
        [0.2511, 0.4906, 0.5676, 0.0026],
        [0.5535, 0.0063, 0.1886, 0.9845]])
Datatype of tensor: torch.float32
Shape of tensor: torch.Size([3, 4])
Device tensor is stored on: cpu


Two main ways of performing multiplication in neural networks and deep learning:
1. Element-wise multiplication
2. Matrix mutlipcation
There are two main rules that performing matrix multiplications needs to satisfy:
1. The **inner dimensions** must match:
- `(3, 2) @ (3, 2)` won't work
- `(2, 3) @ (3, 2)` will work
- `(3, 2) @ (2, 3)` will work
2. The resulting matrix has the shape of the **outer dimensions**


In [23]:
tensor = torch.tensor([1, 2, 3])
print(tensor, "*", tensor, "=", tensor * tensor)

tensor([1, 2, 3]) * tensor([1, 2, 3]) = tensor([1, 4, 9])


### We should always try to use torch's implementation of matrix operations, because it is made for speed and optimized better than by hand, and less code

In [24]:
%%time
torch.matmul(tensor, tensor)
value = 0
for i in range(len(tensor)):
    value += tensor[i] * tensor[i]
    print(value)


tensor(1)
tensor(5)
tensor(14)
CPU times: user 2.17 ms, sys: 124 μs, total: 2.29 ms
Wall time: 1.95 ms


In [25]:
%%time
torch.matmul(tensor, tensor)

CPU times: user 134 μs, sys: 14 μs, total: 148 μs
Wall time: 138 μs


tensor(14)

In [26]:
tensor@tensor # matrix multiplication  shorthand

tensor(14)

In [27]:
#shapes for matrix multiplication
tensor_A = torch.tensor([[1, 2],
                          [3, 4],
                          [5, 6]])
tensor_B = torch.tensor([[7, 8],
                          [9, 10],
                          [11, 12]])
print(tensor_A.shape, tensor_B.shape)

torch.Size([3, 2]) torch.Size([3, 2])


In [28]:
tensor_A.shape, tensor_B.shape

(torch.Size([3, 2]), torch.Size([3, 2]))

In [29]:
tensor_B.T, tensor_B.T.shape

(tensor([[ 7,  9, 11],
         [ 8, 10, 12]]),
 torch.Size([2, 3]))

To fix our tensor shape issues we can use **transpose**, which maniuplates the shape of the tensor by switching the axes or dimensions of a given tensor

In [30]:
# The operation works when tensor_B is transposed
print(f"Original shapes: tensor_A = {tensor_A.shape}, tensor_B = {tensor_B.shape}\n")
print(f"New shapes: tensor_A = {tensor_A.shape} (same as above), tensor_B.T = {tensor_B.T.shape}\n")
print(f"Multiplying: {tensor_A.shape} * {tensor_B.T.shape} <- inner dimensions match\n")
print("Output:\n")
output = torch.matmul(tensor_A, tensor_B.T)
print(output) 
print(f"\nOutput shape: {output.shape}")

Original shapes: tensor_A = torch.Size([3, 2]), tensor_B = torch.Size([3, 2])

New shapes: tensor_A = torch.Size([3, 2]) (same as above), tensor_B.T = torch.Size([2, 3])

Multiplying: torch.Size([3, 2]) * torch.Size([2, 3]) <- inner dimensions match

Output:

tensor([[ 23,  29,  35],
        [ 53,  67,  81],
        [ 83, 105, 127]])

Output shape: torch.Size([3, 3])


## Finding the min, max, mean, sum, etc(tensor aggregation)

In [31]:
x = torch.arange(0, 100, 10)
# torch.squeeze() - removaes all the dimensions from a target tensor
print(f"previous tesnor ")

previous tesnor 


In [32]:
#Find the max and min
print(torch.max(x), x.max(), torch.min(x), x.min())

tensor(90) tensor(90) tensor(0) tensor(0)


In [33]:
x = torch.arange(1., 10.)
x, x.shape

(tensor([1., 2., 3., 4., 5., 6., 7., 8., 9.]), torch.Size([9]))

In [34]:
# Stack tensors on top of each other
x_reshaped = x.reshape(1,9)
x_stacked = torch.stack([x, x, x, x], dim=0) # try changing dim to dim=1 and see what happens
x_stacked = torch.stack([x, x, x, x], dim=1) # try changing dim to dim=1 and see what happens     
x_stacked                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                              

tensor([[1., 1., 1., 1.],
        [2., 2., 2., 2.],
        [3., 3., 3., 3.],
        [4., 4., 4., 4.],
        [5., 5., 5., 5.],
        [6., 6., 6., 6.],
        [7., 7., 7., 7.],
        [8., 8., 8., 8.],
        [9., 9., 9., 9.]])

In [35]:
z = x.view(1, 9)
z, z.shape

(tensor([[1., 2., 3., 4., 5., 6., 7., 8., 9.]]), torch.Size([1, 9]))

In [36]:
x_reshaped.squeeze().shape
x_squeezed = x_reshaped.squeeze()

In [37]:
#Add an extra dimension with unsqueeze
x_unsqueezed = x_squeezed.unsqueeze(dim=0)
print(x_unsqueezed, x_unsqueezed.shape)

tensor([[1., 2., 3., 4., 5., 6., 7., 8., 9.]]) torch.Size([1, 9])


In [39]:
x_original = torch.rand(size=(224, 224, 3)) # [height, width, color channels]2, 
x_permuted = x_original.permute(2, 0, 1)
print(f"Previous ")
x = torch.arange(1, 10).reshape(1, 3, 3)
x, x.shape

Previous 


(tensor([[[1, 2, 3],
          [4, 5, 6],
          [7, 8, 9]]]),
 torch.Size([1, 3, 3]))

In [41]:
x[0], x[0][0], x[0][0][0]

(tensor([[1, 2, 3],
         [4, 5, 6],
         [7, 8, 9]]),
 tensor([1, 2, 3]),
 tensor(1))

In [44]:
#You can also use : to access all elements in a dimension
#Get all elements of the 0th and 1st dimensions abut only index 1 of 2nd dimension
x[:, :, 1], x[:, 1, 1]

(tensor([[2, 5, 8]]), tensor([5]))

In [47]:
import numpy as np
array = np.arange(1.0, 8.0)
tensor = torch.from_numpy(array)
array, tensor

(array([1., 2., 3., 4., 5., 6., 7.]),
 tensor([1., 2., 3., 4., 5., 6., 7.], dtype=torch.float64))

In [49]:
array = array+1

array, tensor.dtype

(array([2., 3., 4., 5., 6., 7., 8.]), torch.float64)

In [50]:
numpy_tensor = tensor.numpy()
tensor, numpy_tensor
#numpy default is float64, but tensor is float32

(tensor([1., 2., 3., 4., 5., 6., 7.], dtype=torch.float64),
 array([1., 2., 3., 4., 5., 6., 7.]))

In [54]:
#reproducibility- trying to take the random out of random
# Create two random tensors
random_tensor_1 = torch.rand(3, 4)
random_tensor_2 = torch.rand(3, 4)
print(random_tensor_1, random_tensor_2)
print(random_tensor_1 == random_tensor_2)

tensor([[0.1757, 0.1252, 0.9661, 0.7985],
        [0.8991, 0.1988, 0.7903, 0.7705],
        [0.4677, 0.8181, 0.8431, 0.6778]]) tensor([[0.9297, 0.7011, 0.4250, 0.3225],
        [0.1023, 0.6068, 0.6159, 0.1308],
        [0.3623, 0.8023, 0.2673, 0.7045]])
tensor([[False, False, False, False],
        [False, False, False, False],
        [False, False, False, False]])


In [56]:
RANDOM_SEED = 63
torch.manual_seed(RANDOM_SEED)
random_tensor_3 = torch.rand(3, 4)
torch.manual_seed(RANDOM_SEED)
random_tensor_4 = torch.rand(3, 4)
print(random_tensor_3, random_tensor_4)

tensor([[0.8089, 0.4226, 0.4395, 0.5875],
        [0.3205, 0.3477, 0.5722, 0.3869],
        [0.1779, 0.2663, 0.0026, 0.1007]]) tensor([[0.8089, 0.4226, 0.4395, 0.5875],
        [0.3205, 0.3477, 0.5722, 0.3869],
        [0.1779, 0.2663, 0.0026, 0.1007]])


In [59]:
device = 'cuda' if torch.cuda.is_available() else 'cpu'
device

'cpu'

In [58]:
tesnor = torch.tensor([1, 2, 3])
print(tensor)

tensor([1., 2., 3., 4., 5., 6., 7.], dtype=torch.float64)


In [61]:
tensor_on_gpu = tensor.to(device)
tensor_on_gpu

tensor([1., 2., 3., 4., 5., 6., 7.], dtype=torch.float64)

In [ ]:
#If tensor is on GPU, can't transfer it to numpy
tensor_back_on_cppu = tensor_on_gpu.to("cpu")

