In [33]:
import torch
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
print(torch.__version__)


2.5.1


In [34]:
scalar = torch.tensor(7)
vector = torch.tensor([7,7])
print(scalar, vector, scalar.ndim, scalar.item(), vector.shape)


tensor(7) tensor([7, 7]) 0 7 torch.Size([2])


In [35]:
MATRIX = torch.tensor([[7, 8],
                      [9, 10]])
MATRIX

tensor([[ 7,  8],
        [ 9, 10]])

In [36]:
MATRIX[1], MATRIX.shape

(tensor([ 9, 10]), torch.Size([2, 2]))

In [37]:
# Create a random tensor of size [3, 4]
random_tensor = torch.rand(3,3, 3)
random_tensor

tensor([[[0.1202, 0.1204, 0.6725],
         [0.7044, 0.4027, 0.1075],
         [0.4669, 0.9522, 0.8802]],

        [[0.4254, 0.4547, 0.7628],
         [0.8989, 0.8594, 0.9428],
         [0.0999, 0.6546, 0.0843]],

        [[0.9713, 0.4810, 0.5337],
         [0.2071, 0.0717, 0.6075],
         [0.8643, 0.1143, 0.4903]]])

In [38]:
random_image_size_tensor = torch.rand(size=(224, 224, 3)) #height, width, colour channel
random_image_size_tensor.shape, random_image_size_tensor.ndim

(torch.Size([224, 224, 3]), 3)

In [39]:
zero = torch.zeros(size=(3,4))
zero

tensor([[0., 0., 0., 0.],
        [0., 0., 0., 0.],
        [0., 0., 0., 0.]])

In [40]:
ones = torch.ones(size=(3,4))
ones

tensor([[1., 1., 1., 1.],
        [1., 1., 1., 1.],
        [1., 1., 1., 1.]])

##Creating a range of tensors and tensors-like

In [41]:
#use torch.arange()
#torch.range is deprecated
torch.arange(0, 10)

tensor([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [42]:
one_to_ten = torch.arange(start=1, end=11, step=1)
one_to_ten

tensor([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10])

In [43]:
ten_zeros = torch.zeros_like(input=one_to_ten)
ten_zeros

tensor([0, 0, 0, 0, 0, 0, 0, 0, 0, 0])

In [44]:
float_32_tensor = torch.tensor([3.0, 6.0, 9.0], 
                               dtype=None, # datatype is a tensor of float32
                               device="cpu",  # device is the CPU
                               requires_grad=False) #wether or not to track gradients for this tensor
# autograd should not track the gradient for this tensor
float_32_tensor

tensor([3., 6., 9.])

In [45]:
float_32_tensor.dtype

torch.float32

In [46]:
float_16_tensor = float_32_tensor.to(dtype=torch.float16)
float_16_tensor

tensor([3., 6., 9.], dtype=torch.float16)

In [47]:
float_16_tensor * float_32_tensor

tensor([ 9., 36., 81.])

In [48]:
int_32_tensor = torch.tensor([3, 6, 9], dtype=torch.int32)
int_32_tensor

tensor([3, 6, 9], dtype=torch.int32)

In [49]:
float_32_tensor * int_32_tensor

tensor([ 9., 36., 81.])

In [50]:
int_32_tensor = torch.tensor([3, 6, 9], dtype=torch.float32)
int_32_tensor

tensor([3., 6., 9.])

In [51]:
float_32_tensor * int_32_tensor

tensor([ 9., 36., 81.])

In [52]:
some_tensor = torch.rand(size=(3,4))
some_tensor

tensor([[0.7401, 0.5476, 0.2835, 0.7273],
        [0.2563, 0.1386, 0.8853, 0.8645],
        [0.5402, 0.7125, 0.6954, 0.5165]])

In [53]:
#Find out  details about some tensor
some_tensor.size(), some_tensor.shape, some_tensor.ndim, some_tensor.device, some_tensor.dtype

(torch.Size([3, 4]), torch.Size([3, 4]), 2, device(type='cpu'), torch.float32)

In [54]:
print(some_tensor)
print(f"Datatype of tensor: {some_tensor.dtype}")
print(f"Shape of tensor: {some_tensor.shape}")
print(f"Device tensor is stored on: {some_tensor.device}")

#Matrix multiplication 


tensor([[0.7401, 0.5476, 0.2835, 0.7273],
        [0.2563, 0.1386, 0.8853, 0.8645],
        [0.5402, 0.7125, 0.6954, 0.5165]])
Datatype of tensor: torch.float32
Shape of tensor: torch.Size([3, 4])
Device tensor is stored on: cpu


Two main ways of performing multiplication in neural networks and deep learning:
1. Element-wise multiplication
2. Matrix mutlipcation
There are two main rules that performing matrix multiplications needs to satisfy:
1. The **inner dimensions** must match:
- `(3, 2) @ (3, 2)` won't work
- `(2, 3) @ (3, 2)` will work
- `(3, 2) @ (2, 3)` will work
2. The resulting matrix has the shape of the **outer dimensions**


In [55]:
tensor = torch.tensor([1, 2, 3])
print(tensor, "*", tensor, "=", tensor * tensor)

tensor([1, 2, 3]) * tensor([1, 2, 3]) = tensor([1, 4, 9])


### We should always try to use torch's implementation of matrix operations, because it is made for speed and optimized better than by hand, and less code

In [56]:
%%time
torch.matmul(tensor, tensor)
value = 0
for i in range(len(tensor)):
    value += tensor[i] * tensor[i]
    print(value)


tensor(1)
tensor(5)
tensor(14)
CPU times: user 0 ns, sys: 1.43 ms, total: 1.43 ms
Wall time: 1.07 ms


In [57]:
%%time
torch.matmul(tensor, tensor)

CPU times: user 199 μs, sys: 25 μs, total: 224 μs
Wall time: 138 μs


tensor(14)

In [58]:
tensor@tensor # matrix multiplication  shorthand

tensor(14)

In [59]:
#shapes for matrix multiplication
tensor_A = torch.tensor([[1, 2],
                          [3, 4],
                          [5, 6]])
tensor_B = torch.tensor([[7, 8],
                          [9, 10],
                          [11, 12]])
print(tensor_A.shape, tensor_B.shape)

torch.Size([3, 2]) torch.Size([3, 2])


In [60]:
tensor_A.shape, tensor_B.shape

(torch.Size([3, 2]), torch.Size([3, 2]))

In [61]:
tensor_B.T, tensor_B.T.shape

(tensor([[ 7,  9, 11],
         [ 8, 10, 12]]),
 torch.Size([2, 3]))

In [62]:
# The operation works when tensor_B is transposed
print(f"Original shapes: tensor_A = {tensor_A.shape}, tensor_B = {tensor_B.shape}\n")
print(f"New shapes: tensor_A = {tensor_A.shape} (same as above), tensor_B.T = {tensor_B.T.shape}\n")
print(f"Multiplying: {tensor_A.shape} * {tensor_B.T.shape} <- inner dimensions match\n")
print("Output:\n")
output = torch.matmul(tensor_A, tensor_B.T)
print(output) 
print(f"\nOutput shape: {output.shape}")

Original shapes: tensor_A = torch.Size([3, 2]), tensor_B = torch.Size([3, 2])

New shapes: tensor_A = torch.Size([3, 2]) (same as above), tensor_B.T = torch.Size([2, 3])

Multiplying: torch.Size([3, 2]) * torch.Size([2, 3]) <- inner dimensions match

Output:

tensor([[ 23,  29,  35],
        [ 53,  67,  81],
        [ 83, 105, 127]])

Output shape: torch.Size([3, 3])


In [63]:
x = torch.arange(0,100, 10)
x

tensor([ 0, 10, 20, 30, 40, 50, 60, 70, 80, 90])

In [64]:
print(f"Minimum: {x.min()}")
print(f"Maximum: {x.max()}")
# print(f"Mean: {x.mean()}") # this will error
print(f"Mean: {x.type(torch.float32).mean()}") # won't work without float datatype
print(f"Sum: {x.sum()}")

Minimum: 0
Maximum: 90
Mean: 45.0
Sum: 450
