In [1]:
import torch
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
print(torch.__version__)


2.5.1


In [12]:
scalar = torch.tensor(7)
vector = torch.tensor([7,7])
print(scalar, vector, scalar.ndim, scalar.item(), vector.shape)

tensor(7) tensor([7, 7]) 0 7 torch.Size([2])


In [6]:
MATRIX = torch.tensor([[7, 8],
                      [9, 10]])
MATRIX

tensor([[ 7,  8],
        [ 9, 10]])

In [14]:
MATRIX[1], MATRIX.shape

(tensor([ 9, 10]), torch.Size([2, 2]))

In [17]:
# Create a random tensor of size [3, 4]
random_tensor = torch.rand(3,3, 3)
random_tensor

tensor([[[0.4759, 0.8672, 0.4334],
         [0.4795, 0.0497, 0.7027],
         [0.4252, 0.6566, 0.1834]],

        [[0.4658, 0.6166, 0.5604],
         [0.2353, 0.5355, 0.1708],
         [0.8713, 0.3540, 0.7814]],

        [[0.0046, 0.3161, 0.3930],
         [0.0980, 0.7993, 0.5427],
         [0.8456, 0.9707, 0.0447]]])

In [18]:
random_image_size_tensor = torch.rand(size=(224, 224, 3)) #height, width, colour channel
random_image_size_tensor.shape, random_image_size_tensor.ndim

(torch.Size([224, 224, 3]), 3)

In [20]:
zero = torch.zeros(size=(3,4))
zero

tensor([[0., 0., 0., 0.],
        [0., 0., 0., 0.],
        [0., 0., 0., 0.]])