In [34]:
import torch
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
print(torch.__version__)


2.5.1


In [35]:
scalar = torch.tensor(7)
vector = torch.tensor([7,7])
print(scalar, vector, scalar.ndim, scalar.item(), vector.shape)


tensor(7) tensor([7, 7]) 0 7 torch.Size([2])


In [36]:
MATRIX = torch.tensor([[7, 8],
                      [9, 10]])
MATRIX

tensor([[ 7,  8],
        [ 9, 10]])

In [37]:
MATRIX[1], MATRIX.shape

(tensor([ 9, 10]), torch.Size([2, 2]))

In [38]:
# Create a random tensor of size [3, 4]
random_tensor = torch.rand(3,3, 3)
random_tensor

tensor([[[0.1322, 0.5040, 0.7182],
         [0.3043, 0.7158, 0.3565],
         [0.2376, 0.5955, 0.3016]],

        [[0.5089, 0.3590, 0.5149],
         [0.2011, 0.4989, 0.2899],
         [0.2983, 0.2572, 0.6062]],

        [[0.6458, 0.6495, 0.5491],
         [0.9557, 0.2895, 0.0048],
         [0.6705, 0.8964, 0.6824]]])

In [39]:
random_image_size_tensor = torch.rand(size=(224, 224, 3)) #height, width, colour channel
random_image_size_tensor.shape, random_image_size_tensor.ndim

(torch.Size([224, 224, 3]), 3)

In [40]:
zero = torch.zeros(size=(3,4))
zero

tensor([[0., 0., 0., 0.],
        [0., 0., 0., 0.],
        [0., 0., 0., 0.]])

In [41]:
ones = torch.ones(size=(3,4))
ones

tensor([[1., 1., 1., 1.],
        [1., 1., 1., 1.],
        [1., 1., 1., 1.]])

##Creating a range of tensors and tensors-like

In [42]:
#use torch.arange()
#torch.range is deprecated
torch.arange(0, 10)

tensor([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [43]:
one_to_ten = torch.arange(start=1, end=11, step=1)
one_to_ten

tensor([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10])

In [44]:
ten_zeros = torch.zeros_like(input=one_to_ten)
ten_zeros

tensor([0, 0, 0, 0, 0, 0, 0, 0, 0, 0])

In [47]:
float_32_tensor = torch.tensor([3.0, 6.0, 9.0], 
                               dtype=None, # datatype is a tensor of float32
                               device="cpu",  # device is the CPU
                               requires_grad=False) #wether or not to track gradients for this tensor
# autograd should not track the gradient for this tensor
float_32_tensor

tensor([3., 6., 9.])

In [48]:
float_32_tensor.dtype

torch.float32

In [51]:
float_16_tensor = float_32_tensor.to(dtype=torch.float16)
float_16_tensor

tensor([3., 6., 9.], dtype=torch.float16)

In [52]:
float_16_tensor * float_32_tensor

tensor([ 9., 36., 81.])

In [53]:
int_32_tensor = torch.tensor([3, 6, 9], dtype=torch.int32)
int_32_tensor

tensor([3, 6, 9], dtype=torch.int32)

In [54]:
float_32_tensor * int_32_tensor

tensor([ 9., 36., 81.])

In [55]:
int_32_tensor = torch.tensor([3, 6, 9], dtype=torch.float32)
int_32_tensor

tensor([3., 6., 9.])

In [56]:
float_32_tensor * int_32_tensor

tensor([ 9., 36., 81.])

In [57]:
some_tensor = torch.rand(size=(3,4))
some_tensor

tensor([[0.8554, 0.6782, 0.3598, 0.4641],
        [0.8764, 0.4659, 0.2393, 0.8903],
        [0.0902, 0.5143, 0.2580, 0.5246]])

In [58]:
#Find out  details about some tensor
some_tensor.size(), some_tensor.shape, some_tensor.ndim, some_tensor.device, some_tensor.dtype

(torch.Size([3, 4]), torch.Size([3, 4]), 2, device(type='cpu'), torch.float32)

In [ ]:
print(some_tensor)
print(f"Datatype of tensor: {some_tensor.dtype}")
print(f"Shape of tensor: {some_tensor.shape}")
print(f"Device tensor is stored on: {some_tensor.device}")